In [46]:
import pandas as pd
df = pd.read_csv("policy/avg_policy.csv")
columns = df.columns
df.head()

,PHASE,ROLE,HAND,BOARD,POT,RATIO,SPR,HEROBOARD,PROB_FOLD,PROB_CHECK,PROB_CALL,PROB_RAISE,PROB_ALL-IN
0,PREFLOP,SB,Q3s,0,4,2,6,0,0.70,0.0,0.0,0.30,0.0
1,PREFLOP,SB,Q3s,0,18,4,0,0,0.70,0.0,0.0,0.30,0.0
2,PREFLOP,BB,K6s,0,3,0,6,0,0.50,0.0,0.0,0.50,0.0
3,PREFLOP,BTN,A2s,0,2,4,6,0,0.55,0.0,0.0,0.45,0.0
4,PREFLOP,SB,74o,0,4,2,6,0,0.95,0.0,0.0,0.05,0.0

In [47]:
for column in columns:
    print(df[column].value_counts())
    print("-" * 100)

PHASE
FLOP       117844
TURN        46101
RIVER       15672
PREFLOP      8192
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
ROLE
BB     79653
SB     65378
BTN    42778
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
HAND
92s    2073
42s    2012
53s    1988
63s    1979
82s    1977
       ...
Q6o     609
QJo     601
Q7o     580
KJo     569
AKo     544
Name: count, Length: 169, dtype: int64
----------------------------------------------------------------------------------------------------
BOARD
2     34162
8     24817
0     19592
5     19279
1     15039
7     12769
6     10895
3     10300
4      9302
11     8505
14     6635
9      6243
10     4672
13     2975
12     2624
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
POT
9     28334
7     25366
18    23761
6     20634
8     19313
10    16763
5     12568
3     10998
11     9549
4      8974
12     5867
21     4296
13      873
2       338
14      136
19       26
15       13
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
RATIO
0    91730
2    34451
4    23956
1    19998
3    17674
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
SPR
6    63138
5    54301
4    35713
0    28083
3     6432
2      142
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
HEROBOARD
4    89053
0    41327
5    35838
7    16073
9     3413
6     1858
8      247
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
PROB_FOLD
0.90    22481
0.85    18386
0.80    17768
0.95    12610
0.00    11315
0.55     9510
0.75     8425
0.93     7809
0.70     7449
0.50     6756
0.40     6261
0.83     5656
0.60     5369
0.87     5044
0.65     4212
0.45     4056
0.98     4048
1.00     2926
0.62     2778
0.68     2474
0.58     2203
0.47     1831
0.92     1765
0.97     1739
0.88     1558
0.77     1553
0.53     1362
0.67     1360
0.78     1337
0.52     1291
0.30     1149
0.20     1100
0.25      979
0.73      689
0.43      687
0.28      664
0.10      640
0.42      569
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
PROB_CHECK
0.0    187809
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
PROB_CALL
0.0    187809
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
PROB_RAISE
0.10    22481
0.15    18386
0.20    17768
0.05    12610
1.00    10465
0.45     9510
0.25     8425
0.07     7809
0.30     7449
0.50     6756
0.60     6261
0.17     5656
0.40     5369
0.13     5044
0.35     4212
0.55     4056
0.02     4048
0.00     2926
0.38     2778
0.32     2474
0.42     2203
0.53     1831
0.75     1829
0.08     1765
0.03     1739
0.12     1558
0.23     1553
0.47     1362
0.33     1360
0.22     1337
0.48     1291
0.70     1149
0.80     1100
0.27      689
0.57      687
0.72      664
0.90      640
0.58      569
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
PROB_ALL-IN
0.00    186959
0.25       850
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------

In [48]:
df_preflop = df[df['PHASE'] == 'PREFLOP']
df_preflop_sb = df_preflop[df_preflop['ROLE'] == 'SB']
df_preflop_sb.describe()

,BOARD,POT,RATIO,SPR,HEROBOARD,PROB_FOLD,PROB_CHECK,PROB_CALL,PROB_RAISE,PROB_ALL-IN
count,2798.0,2798.000000,2798.000000,2798.000000,2798.0,2798.000000,2798.0,2798.0,2798.000000,2798.000000
mean,0.0,9.171194,2.203002,4.319871,0.0,0.678549,0.0,0.0,0.320200,0.001251
std,0.0,4.625982,0.849971,1.822545,0.0,0.269776,0.0,0.0,0.267193,0.017643
min,0.0,2.000000,1.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000
25%,0.0,6.000000,2.000000,4.000000,0.0,0.550000,0.0,0.0,0.120000,0.000000
50%,0.0,9.000000,2.000000,5.000000,0.0,0.780000,0.0,0.0,0.220000,0.000000
75%,0.0,11.000000,3.000000,6.000000,0.0,0.880000,0.0,0.0,0.450000,0.000000
max,0.0,21.000000,4.000000,6.000000,0.0,1.000000,0.0,0.0,1.000000,0.250000